# This file was generated by GoReleaser. DO NOT EDIT.
cask "radcli" do
  name "radcli"
  desc "Reddit Ads from the terminal"
  homepage "https://github.com/lloydhumphreys/radcli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rad"

  on_macos do
    on_intel do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_darwin_amd64.tar.gz"
      sha256 "c2338aaab3e6cba641d0c7e2a7190c072cca4c7fd569b43c1d1e71aee07dccaa"
    end
    on_arm do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_darwin_arm64.tar.gz"
      sha256 "cc9b692cf0797dab2a076664efc0711534c0cfb5d594eac68b5a88a813a1785d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_linux_amd64.tar.gz"
      sha256 "10fdcae71c7bae3ef6c7366504b0b6a11879195d074b325b87b81ca8f892b436"
    end
    on_arm do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_linux_arm64.tar.gz"
      sha256 "a5db67e79765a4b8d72e35d22356179afe507b6d01794b4e773267e31218838f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rad"]
    end
  end

  # No zap stanza required
end
