# This file was generated by GoReleaser. DO NOT EDIT.
cask "radcli" do
  name "radcli"
  desc "Reddit Ads from the terminal"
  homepage "https://github.com/lloydhumphreys/radcli"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rad"

  on_macos do
    on_intel do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_darwin_amd64.tar.gz"
      sha256 "66e459ee793734206c93d0d951af656492f1a16ea1896c000d8956d696cc1717"
    end
    on_arm do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_darwin_arm64.tar.gz"
      sha256 "6013127e4bbe4263a5bff6d3d7e6904f0d324573764bfff1e7aea50b8decea53"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_linux_amd64.tar.gz"
      sha256 "a63fa455090a380a0cbd56596b2bd9dadb6912d180f5c4f0b7cba5092d8a35c5"
    end
    on_arm do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_linux_arm64.tar.gz"
      sha256 "8c21ca7c17eeebc8a746c5b9559e5092596e749007635d334b7313c67685a291"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rad"]
    end
  end

  # No zap stanza required
end
