# This file was generated by GoReleaser. DO NOT EDIT.
cask "radcli" do
  name "radcli"
  desc "Reddit Ads from the terminal"
  homepage "https://github.com/lloydhumphreys/radcli"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rad"

  on_macos do
    on_intel do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_darwin_amd64.tar.gz"
      sha256 "e61f7523a357b704a498eeb60267a515dbbf971725b785581c32d6f135c9c18f"
    end
    on_arm do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_darwin_arm64.tar.gz"
      sha256 "db031acef66ad98a486e28fc80776e20c24b009b13935988cd6a279f8b9d5e36"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_linux_amd64.tar.gz"
      sha256 "094e2b4d8c768cc4a54f5774c4b9da46c33e76e7b677008e1ff415da9a602be2"
    end
    on_arm do
      url "https://github.com/lloydhumphreys/radcli/releases/download/v#{version}/radcli_#{version}_linux_arm64.tar.gz"
      sha256 "c0ef3d898648847e25a59e9c67a0aebe57ce4ffe80cb75868454d7e4f4794e96"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rad"]
    end
  end

  # No zap stanza required
end
